# -*- conf -*-

shell=/usr/bin/zsh

app-id=foot
title=foot
locked-title=no

font=JetBrainsMono NF:size=12
font-size-adjustment=0.5
letter-spacing=0
horizontal-letter-offset=0
vertical-letter-offset=0
box-drawings-uses-font-glyphs=no
dpi-aware=on

initial-window-mode=windowed
pad=0x0
resize-delay-ms=100

bold-text-in-bright=no
word-delimiters=,│`|:"'()[]{}<>
selection-target=primary

[bell]
urgent=no
notify=no

[scrollback]
lines=1000
multiplier=3.0
indicator-position=relative
indicator-format=""

[cursor]
style=block
#color=<inverse foreground/background>
blink=no
beam-thickness=1.5

[mouse]
hide-when-typing=no
alternate-scroll-mode=yes

[colors]
alpha=0.95
background=000000
foreground=dddddd

# Normal/regular colors (color palette 0-7)
regular0=073642  # black
regular1=dc322f  # red
regular2=859900  # green
regular3=b58900  # yellow
regular4=268bd2  # blue
regular5=d33682  # magenta
regular6=2aa198  # cyan
regular7=eee8d5  # white

# Bright colors (color palette 8-15)
bright0=08404f   # bright black
bright1=e35f5c   # bright red
bright2=9fb700   # bright green
bright3=d9a400   # bright yellow
bright4=4ba1de   # bright blue
bright5=dc619d   # bright magenta
bright6=32c1b6   # bright cyan
bright7=ffffff   # bright white

16=fab387
17=f5e0dc

selection-foreground=cdd6f4
selection-background=414356

search-box-no-match=11111b f38ba8
search-box-match=cdd6f4 313244

jump-labels=11111b fab387
urls=89b4fa

